### PR TITLE
MRG: Add mne logger

### LINKED ISSUE #105: Use the MNE logger to set the verbosity
I have been using PyPREP a bit (version 0.3.1, pip install) and I really like it for now.
Would it be possible to add a verbose argument to limit the prints? Alternatively, moving the print to a logger with a `set_log_level` function would work out too.

Example: `print("Executing RANSAC\nThis may take a while, so be patient...")`

When running a preprocessing pipeline with several steps, one of which is PyPREP, the relevant logging from the pipeline can be completely overwhelmed by the prints from PyPREP, especially if you run it as I do on e.g. 40 cores at once.

### PR DESCRIPTION
**Pull request by mscheltienne**
Closes #105.

I had this on my namespace for a while... (Oct 22. 2021) and I didn't take the time to finish it. 
If I recall correctly, it's missing the ProgressBar class for the 10%... 20%... 30%... print output by the RANSAC (probably the most annoying one when I run this on 40 cores 😅). 
I'll double-check the diff, make sure I didn't miss anything and add the ProgressBar for RANSAC.

Mathieu

### CODE REVIEW

**Comment by mscheltienne** [comment]
Also have to fix a couple of logs, as it seems I just did a `replace`

**Comment by mscheltienne** [comment]
image

Looks like this is working. And it does get disabled if I change the loglevel of MNE.

**Review by sappelhoff — COMMENTED** [review]
LGTM, thanks!

Please:

- add yourself here: https://github.com/sappelhoff/pyprep/blob/4a91d31782717c60e7c9e8814f68a83645f54475/.zenodo.json#L43
- and to the list of authors here: https://github.com/sappelhoff/pyprep/blob/master/docs/whats_new.rst (don't forget to also put a link at the bottom of the doc)
- finally, please prepare a short changelog entry (for syntax, see the previous entries)

We can ignore the codecov check.
Previously there was some RNG issue in the tests, that has now disappeared ... still a bit weird - but in any case unrelated to your changes.

**Comment by mscheltienne** [comment]
Done

**Review by sappelhoff — APPROVED** [review]

**Comment by sappelhoff** [comment]
Thanks @mscheltienne

**Pull request merged**
